AgendaDapper/Models/Cliente.cs
using System.ComponentModel.DataAnnotations;

namespace AgendaDapper.Models
{
    public class Cliente
    {
        [Key]
        public int IdCliente { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set;}
        public long Telefono { get; set; }
        public string Email { get; set; }
        public string Pais { get; set;}
        public DateTime  FechaCreacion { get; set;}
    }
}

AgendaDapper/Models/ErrorViewModel.cs
namespace AgendaDapper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AgendaDapper/Controllers/InicioController.cs
using AgendaDapper.Models;
using AgendaDapper.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AgendaDapper.Controllers
{
    public class InicioController : Controller
    {
        public readonly IRepositorio _repo;

        public InicioController(IRepositorio repo)
        {
            _repo = repo;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_repo.GetClientes());
        }

        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear([Bind("IdCliente, Nombres, Apellidos, Telefono, Email, Pais, FechaCreacion")] Cliente cliente)
        {
            if(ModelState.IsValid)
            {
                _repo.AgregarCliente(cliente);  
                //SI SE INSERT CORRECTAMETE SEW REDIRECCIONE AL INDEX 
                return RedirectToAction(nameof(Index));
            }

            return View(cliente);

        }

        //Obtengo el cliente para Editar
        [HttpGet]
        public IActionResult Editar(int? id)
        {
            var cliente = _repo.GetCliente(id.GetValueOrDefault());
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(int id, [Bind("IdCliente, Nombres, Apellidos, Telefono, Email, Pais, FechaCreacion")] Cliente cliente)
        {
            if (id != cliente.IdCliente)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                _repo.ActualizarCliente(cliente);
                return RedirectToAction(nameof(Index));
            }

            return View(cliente);
        }


        //Obtengo el cliente para Borrar
        [HttpGet]
        public IActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _repo.BorrarCliente(id.GetValueOrDefault());
            return RedirectToAction(nameof(Index));
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AgendaDapper/Views/Inicio/Crear.cshtml
@model AgendaDapper.Models.Cliente
@{
    ViewData["Title"] = "Crear Cliente";
}

<h1>Crear Nuevo Cliente</h1>

<div class="row" id="contenedor1">
    <div class="col-4 offset-4">
        <form asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />

            </div>

            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="FechaCreacion" class="control-label"></label>
                <input asp-for="FechaCreacion" type="date" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>

            <div class="form-group row mt-4">
                <div class="col-6"> 
                    <input type="submit" value="Crear Cliente" class="btn btn-primary form-control" />
                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-warning form-control">Volver a lista</a>
                </div>
            </div>
        </form>
    </div>
</div>

AgendaDapper/Views/Inicio/Editar.cshtml
@model AgendaDapper.Models.Cliente
@{
    ViewData["Title"] = "Editar Cliente";
}

<h1>Editar Cliente</h1>

<div class="row" id="contenedor1">
    <div class="col-4 offset-4">
        <form asp-action="Editar">

            <!-- Enviar IdCliente como campo oculto -->
            <input type="hidden" asp-for="IdCliente"/>


            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />

            </div>

            <div class="form-group">
                <label asp-for="Apellidos" class="control-label"></label>
                <input asp-for="Apellidos" class="form-control" />
                <span asp-validation-for="Apellidos" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Pais" class="control-label"></label>
                <input asp-for="Pais" class="form-control" />
                <span asp-validation-for="Pais" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="FechaCreacion" class="control-label"></label>
                <input asp-for="FechaCreacion" type="date" class="form-control" />
                <span asp-validation-for="FechaCreacion" class="text-danger"></span>
            </div>

            <div class="form-group row mt-4">
                <div class="col-6">
                    <input type="submit" value="Editar Cliente" class="btn btn-outline-danger form-control" />
                </div>
                <div class="col-6">
                    <a asp-action="Index" class="btn btn-warning form-control">Volver a lista</a>
                </div>
            </div>
        </form>
    </div>
</div>

AgendaDapper/Views/Inicio/Index.cshtml
@model IEnumerable<AgendaDapper.Models.Cliente>
@{
    ViewData["Title"] = "Lista de Clientes";
}

<h1>Administracion de Clientes</h1>

<p>
    <a asp-action="Crear" class="btn btn-primary">Agregar Cliente</a>

</p>

    <table class="table">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.IdCliente)</th>
                <th>@Html.DisplayNameFor(model => model.Nombres)</th>
                <th>@Html.DisplayNameFor(model => model.Apellidos)</th>
                <th>@Html.DisplayNameFor(model => model.Telefono)</th>
                <th>@Html.DisplayNameFor(model => model.Email)</th>
                <th>@Html.DisplayNameFor(model => model.Pais)</th>
                <th>@Html.DisplayNameFor(model => model.FechaCreacion)</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
        {
            <tr>
                <th>@Html.DisplayFor(modelItem => item.IdCliente)</th>
                <th>@Html.DisplayFor(modelItem => item.Nombres)</th>
                <th>@Html.DisplayFor(modelItem => item.Apellidos)</th>
                <th>@Html.DisplayFor(modelItem => item.Telefono)</th>
                <th>@Html.DisplayFor(modelItem => item.Email)</th>
                <th>@Html.DisplayFor(modelItem => item.Pais)</th>
                <th>@Html.DisplayFor(modelItem => item.FechaCreacion)</th>

                <th>
                    <a asp-action="Editar" asp-route-id="@item.IdCliente" class="btn btn-info"> Editar </a>
                    <a asp-action="Borrar" asp-route-id="@item.IdCliente" class="btn btn-danger">Borrar</a>
                </th>

            </tr>

        }
        </tbody>
    </table>

AgendaDapper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AgendaDapper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AgendaDapper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Inicio" asp-action="Index">AgendaDapper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AgendaDapper - <a asp-area="" asp-controller="Inicio" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>